/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.traveltracker;

/**
 *
 * @author Robert Link
 */
public class UpravitFormNoDialog extends javax.swing.JFrame {

    VyletDao vyletDao = VyletDaoFactory.INSTANCE.getVyletDao();
     private Vylet vylet;
    
    public UpravitFormNoDialog(Vylet vylet) {
        this.vylet=vylet;
        initComponents();
    }

    private UpravitFormNoDialog() {
       initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatumDatePicker = new org.jdesktop.swingx.JXDatePicker();
        KrajinaLabel = new javax.swing.JLabel();
        MestoLabel = new javax.swing.JLabel();
        PamiatkaLabel = new javax.swing.JLabel();
        DatumLabel = new javax.swing.JLabel();
        KrajinaTextField = new javax.swing.JTextField();
        MestoTextField = new javax.swing.JTextField();
        PamiatkaTextField = new javax.swing.JTextField();
        UpravitKrajinaButton = new javax.swing.JButton();
        UpravitMestoButton = new javax.swing.JButton();
        UpravitPamiatkaButton = new javax.swing.JButton();
        UpravitDatumButton = new javax.swing.JButton();
        NavstiveneLabel = new javax.swing.JLabel();
        HodnotenieLabel = new javax.swing.JLabel();
        PodrobnostiLabel = new javax.swing.JLabel();
        PoznamkyLabel = new javax.swing.JLabel();
        NavstiveneTextField = new javax.swing.JTextField();
        HodnotenieTextField = new javax.swing.JTextField();
        PodrobnostiTextField = new javax.swing.JTextField();
        PoznamkyTextField = new javax.swing.JTextField();
        UpravitNavstiveneButton = new javax.swing.JButton();
        UpravitHodnotenieButton = new javax.swing.JButton();
        UpravitPodrobnostiButton = new javax.swing.JButton();
        UpravitPoznamkyButton = new javax.swing.JButton();
        DokonceneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KrajinaLabel.setText("Krajina");

        MestoLabel.setText("Mesto");

        PamiatkaLabel.setText("Pamiatka");

        DatumLabel.setText("Datum");

        UpravitKrajinaButton.setText("Upraviť");
        UpravitKrajinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravitKrajinaButtonActionPerformed(evt);
            }
        });

        UpravitMestoButton.setText("Upraviť");
        UpravitMestoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravitMestoButtonActionPerformed(evt);
            }
        });

        UpravitPamiatkaButton.setText("Upraviť");
        UpravitPamiatkaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravitPamiatkaButtonActionPerformed(evt);
            }
        });

        UpravitDatumButton.setText("Upraviť");
        UpravitDatumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravitDatumButtonActionPerformed(evt);
            }
        });

        NavstiveneLabel.setText("Navstivene");

        HodnotenieLabel.setText("Hodnotenie");

        PodrobnostiLabel.setText("Podrobnosti");

        PoznamkyLabel.setText("Poznamky");

        UpravitNavstiveneButton.setText("Upraviť");
        UpravitNavstiveneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravitNavstiveneButtonActionPerformed(evt);
            }
        });

        UpravitHodnotenieButton.setText("Upraviť");
        UpravitHodnotenieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravitHodnotenieButtonActionPerformed(evt);
            }
        });

        UpravitPodrobnostiButton.setText("Upraviť");
        UpravitPodrobnostiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravitPodrobnostiButtonActionPerformed(evt);
            }
        });

        UpravitPoznamkyButton.setText("Upraviť");
        UpravitPoznamkyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravitPoznamkyButtonActionPerformed(evt);
            }
        });

        DokonceneButton.setText("Dokončené");
        DokonceneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DokonceneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DatumLabel)
                    .addComponent(KrajinaLabel)
                    .addComponent(MestoLabel)
                    .addComponent(PamiatkaLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DatumDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(KrajinaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addComponent(MestoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PamiatkaTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpravitKrajinaButton)
                    .addComponent(UpravitMestoButton)
                    .addComponent(UpravitPamiatkaButton)
                    .addComponent(UpravitDatumButton))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(HodnotenieLabel)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NavstiveneLabel)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NavstiveneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(HodnotenieTextField))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(UpravitHodnotenieButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(UpravitNavstiveneButton))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DokonceneButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PodrobnostiLabel)
                                .addComponent(PoznamkyLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(PoznamkyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(UpravitPoznamkyButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(PodrobnostiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(UpravitPodrobnostiButton))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KrajinaLabel)
                    .addComponent(KrajinaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpravitKrajinaButton)
                    .addComponent(NavstiveneLabel)
                    .addComponent(NavstiveneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpravitNavstiveneButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HodnotenieLabel)
                            .addComponent(HodnotenieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpravitHodnotenieButton))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MestoLabel)
                            .addComponent(MestoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpravitMestoButton))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpravitPamiatkaButton)
                            .addComponent(PamiatkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PamiatkaLabel)
                            .addComponent(PodrobnostiLabel)
                            .addComponent(PodrobnostiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpravitPodrobnostiButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatumLabel)
                    .addComponent(DatumDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpravitDatumButton)
                    .addComponent(PoznamkyLabel)
                    .addComponent(PoznamkyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpravitPoznamkyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(DokonceneButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpravitKrajinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravitKrajinaButtonActionPerformed
        String krajina=  KrajinaTextField.getText();
        vylet.setKrajina( krajina);
        vyletDao.upravitKrajina(vylet);
    }//GEN-LAST:event_UpravitKrajinaButtonActionPerformed

    private void UpravitMestoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravitMestoButtonActionPerformed
       vylet.setMesto( MestoTextField.getText());
       vyletDao.upravitMesto(vylet);
    }//GEN-LAST:event_UpravitMestoButtonActionPerformed

    private void UpravitPamiatkaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravitPamiatkaButtonActionPerformed
        vylet.setPrirodna_a_kulturna_pamiatka(PamiatkaTextField.getText());
         vyletDao.upravitPamiatka(vylet);
    }//GEN-LAST:event_UpravitPamiatkaButtonActionPerformed

    private void UpravitDatumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravitDatumButtonActionPerformed
        vylet.setDatum(DatumDatePicker.getDate());
         vyletDao.upravitDatum(vylet);
    }//GEN-LAST:event_UpravitDatumButtonActionPerformed

    private void UpravitNavstiveneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravitNavstiveneButtonActionPerformed
         vylet.setNavstivenost(Boolean.parseBoolean(NavstiveneTextField.getText()));
         vyletDao.upravitNavstivene(vylet);
    }//GEN-LAST:event_UpravitNavstiveneButtonActionPerformed

    private void UpravitHodnotenieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravitHodnotenieButtonActionPerformed
       vylet.setHodnotenie(Integer.parseInt(NavstiveneTextField.getText()));
       vyletDao.upravitHodnotenie(vylet);
    }//GEN-LAST:event_UpravitHodnotenieButtonActionPerformed

    private void UpravitPodrobnostiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravitPodrobnostiButtonActionPerformed
         vylet.setPodrobnosti(PodrobnostiTextField.getText());
          vyletDao.upravitPodrobnosti(vylet);
    }//GEN-LAST:event_UpravitPodrobnostiButtonActionPerformed

    private void UpravitPoznamkyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravitPoznamkyButtonActionPerformed
         vylet.setPoznamka(PoznamkyTextField.getText());
         vyletDao.upravitPoznamky(vylet);
    }//GEN-LAST:event_UpravitPoznamkyButtonActionPerformed

    private void DokonceneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DokonceneButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_DokonceneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpravitFormNoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpravitFormNoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpravitFormNoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpravitFormNoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpravitFormNoDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DatumDatePicker;
    private javax.swing.JLabel DatumLabel;
    private javax.swing.JButton DokonceneButton;
    private javax.swing.JLabel HodnotenieLabel;
    private javax.swing.JTextField HodnotenieTextField;
    private javax.swing.JLabel KrajinaLabel;
    private javax.swing.JTextField KrajinaTextField;
    private javax.swing.JLabel MestoLabel;
    private javax.swing.JTextField MestoTextField;
    private javax.swing.JLabel NavstiveneLabel;
    private javax.swing.JTextField NavstiveneTextField;
    private javax.swing.JLabel PamiatkaLabel;
    private javax.swing.JTextField PamiatkaTextField;
    private javax.swing.JLabel PodrobnostiLabel;
    private javax.swing.JTextField PodrobnostiTextField;
    private javax.swing.JLabel PoznamkyLabel;
    private javax.swing.JTextField PoznamkyTextField;
    private javax.swing.JButton UpravitDatumButton;
    private javax.swing.JButton UpravitHodnotenieButton;
    private javax.swing.JButton UpravitKrajinaButton;
    private javax.swing.JButton UpravitMestoButton;
    private javax.swing.JButton UpravitNavstiveneButton;
    private javax.swing.JButton UpravitPamiatkaButton;
    private javax.swing.JButton UpravitPodrobnostiButton;
    private javax.swing.JButton UpravitPoznamkyButton;
    // End of variables declaration//GEN-END:variables
}
